import { SeriesTags } from '@kakkoii/types/series-tags';

export const tagsData: { label: string, value: SeriesTags }[] = [
  { value: 'Isekai', label: 'Isekai' },
  { value: 'Demony', label: 'Demony' },
  { value: 'Wampiry', label: 'Wampiry' },
  { value: 'Cringe', label: 'Cringe' },
  { value: 'Muzyczne', label: 'Muzyczne' },
  { value: 'Sztuki Walki', label: 'Sztuki Walki' },
  { value: 'Wyścigowe', label: 'Wyścigowe' },
  { value: 'Seinen', label: 'Seinen' },
  { value: 'Magia', label: 'Magia' },
  { value: 'Romans', label: 'Romans' },
  { value: 'Fantasy', label: 'Fantasy' },
  { value: 'Akcja', label: 'Akcja' },
  { value: 'Shounen', label: 'Shounen' },
  { value: 'Shoujo', label: 'Shoujo' },
  { value: 'Samuraje', label: 'Samuraje' },
  { value: 'Psychologiczne', label: 'Psychologiczne' },
  { value: 'Thriller', label: 'Thriller' },
  { value: 'Shoujo Ai', label: 'Shoujo Ai' },
  { value: 'Harem', label: 'Harem' },
  { value: 'Okruchy Życia', label: 'Okruchy Życia' },
  { value: 'Nadprzyrodzone', label: 'Nadprzyrodzone' },
  { value: 'Gra', label: 'Gra' },
  { value: 'Przygodowe', label: 'Przygodowe' },
  { value: 'Sportowe', label: 'Sportowe' },
  { value: 'Mecha', label: 'Mecha' },
  { value: 'Ecchi', label: 'Ecchi' },
  { value: 'Zombie', label: 'Zombie' },
  { value: 'Zagadki/Tajemnice', label: 'Tajemnica' },
  { value: 'Sci-Fi', label: 'Sci-Fi' },
  { value: 'Komedia', label: 'Komedia' },
  { value: 'Wojskowe', label: 'Wojskowe' },
  { value: 'Josei', label: 'Josei' },
  { value: 'Parodia', label: 'Parodia' },
  { value: 'Historyczne', label: 'Historyczne' },
  { value: 'Shounen Ai', label: 'Shounen Ai' },
  { value: 'Horror', label: 'Horror' },
  { value: 'Szkolne', label: 'Szkolne' },
  { value: 'Dramat', label: 'Dramat' },
  { value: 'Super moce', label: 'Super moce' },
];
